// --- CRITICAL SECURITY WARNING ---
// The Gemini API key MUST be provided via the `API_KEY` environment variable.
// For other services, test keys are provided below for development. 
// In a production environment, these should also be moved to secure environment variables.
export const API_KEYS = {
    UNSPLASH: 'iPWfbw_LnSxnFrTdzK5Ch_djZPsLXuimiyrqvKTbYks',
    PEXELS: 'Usb6ZVTXgLa0RT7Gio9zHxVC7th06KO8KIsegYtzVpeZCe7Q9DUC8R30',
};


// AI Model Configuration
export const AI_CONFIG = {
  TEXT_MODEL: 'gemini-2.5-flash',
  IMAGE_MODEL: 'imagen-4.0-generate-001',
};

// Crossword Generation Configuration
export const CROSSWORD_CONFIG = {
  INITIAL_GRID_SIZE: 25,
  MIN_KEYWORDS_FOR_GENERATION: 5, // Min words required from AI analysis to attempt grid generation.
  MIN_PLACED_WORDS_FOR_VALID_GRID: 5, // Min words that must be successfully placed for the grid to be considered valid.
};

// PDF Generation Configuration
export const PDF_CONFIG = {
  MIN_WORD_COUNT_WARNING: 100,
};

// General Application Configuration
export const APP_CONFIG = {
  API_POLITENESS_DELAY_MS: 100, // Reduced delay as we are not hitting image models
  // IMPORTANT: Replace this placeholder with the Stripe Payment Link you create by following DONATION_SETUP.md
  DONATION_LINK_URL: 'https://buy.stripe.com/test_123456789',
};

// UI Configuration for dropdowns, etc.
export const UI_CONFIG = {
  GRADE_LEVELS: [
    { value: '3', label: '3rd Grade' },
    { value: '6', label: '6th Grade' },
    { value: '9', label: '9th Grade' },
    { value: '12', label: '12th Grade' },
  ] as const,
  WORD_COUNTS: [
      { value: 10, label: '10 Words' },
      { value: 15, label: '15 Words' },
      { value: 20, label: '20 Words' },
  ] as const,
  IMAGE_TYPES: [
      { value: 'royalty-free', label: 'Royalty-Free Photo' },
      { value: 'svg', label: 'Abstract SVG' },
  ] as const,
  PUZZLE_TYPES: [
      { value: 'crossword', label: 'Crossword' },
      { value: 'wordsearch', label: 'Word Search' },
      { value: 'wordscramble', label: 'Word Scramble' },
      { value: 'launchedition', label: 'Launch Edition Packet' },
  ] as const,
};

// Defines the freemium model tiers, their pricing, features, and permissions.
// IMPORTANT: Replace the placeholder `priceId` and `productId` with your actual Stripe IDs.
export const USER_TIERS = {
    Free: {
        name: 'Free',
        price: '$0',
        frequency: '/month',
        features: [
            '2 generations per month',
            'Auto-selected royalty-free image',
            '1-month activity history',
            'Standard summary & puzzle',
            'Branded PDF output',
        ],
        permissions: {
            isAutoGenerated: true,
            canEditSearch: false,
            canUploadImage: false,
            canEditSummary: false,
        },
    },
    Monthly: {
        name: 'Monthly Subscriber',
        price: '$3',
        frequency: '/month',
        // Stripe Price ID for the monthly plan
        priceId: 'price_replace_with_your_monthly_price_id',
        // Stripe Product ID for this product
        productId: 'prod_replace_with_your_product_id',
        features: [
            '8 generations per month',
            '4-panel image selection',
            '4-month activity history',
            'Standard summary & puzzle',
            'Branding-free PDF output',
        ],
        permissions: {
            isAutoGenerated: false,
            canEditSearch: false,
            canUploadImage: false,
            canEditSummary: false,
        },
    },
    Yearly: {
        name: 'Yearly Subscriber',
        price: '$30',
        frequency: '/year',
        // Stripe Price ID for the yearly plan
        priceId: 'price_replace_with_your_yearly_price_id',
        // Stripe Product ID for this product
        productId: 'prod_replace_with_your_product_id',
        features: [
            '36 generations per month (12 full packets!)',
            'NEW: All-in-one __Launch Edition__ packet generator',
            'Full activity history',
            'Editable image search',
            'Upload your own images',
            'Branding-free PDF output',
        ],
        permissions: {
            isAutoGenerated: false,
            canEditSearch: true,
            canUploadImage: true,
            canEditSummary: false,
        },
    },
} as const;


// A safe, static fallback image to be used if an image fails to load during PDF generation.
export const STATIC_FALLBACK_IMAGE_DATA_URI = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgc3R5bGU9ImJhY2tncm91bmQtY29sb3I6ICNlY2VlZjQ7Ij48dGV4dCB4PSI1MCUiIHk9IjUwJSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjRweCIgZmlsbD0iIzY0NzQ4YiIgZm9udC1wZWlnaHQ9ImJvbGQiPkltYWdlIE5vdCBBdmFpbGFibGU8L3RleHQ+PC9zdmc+";

// A vertical SVG watermark for PDF branding on free-tier outputs.
export const BRAND_WATERMARK_LOGO_URI = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSI4MDAiPjx0ZXh0IHg9Ii00MDAiIHk9IjI1IiB0cmFuc2Zvcm09InJvdGF0ZSgtOTApIiBzdHlsZT0iZm9udC1mYW1pbHk6c2Fucy1zZXJpZjtmb250LXNpemU6MTZweDtmb250LXdlaWdodDpib2xkO2ZpbGw6IzRhNTU2ODt0ZXh0LWFuY2hvcjptaWRkbGUiPlBMQVkg4pqhIHBsYXktYXBwLmFwcDwvdGV4dD48L3N2Zz4=";